# Generated by Django 4.0.1 on 2022-01-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Kolkata', 'Kolkata')], default=5, max_length=15),
        ),
    ]
