# Generated by Django 4.0.1 on 2022-01-07 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
